### ISSUE TITLE
AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by zhong-yy** [AI4EPS/PhaseNet#63]
Hi, Dr Zhu. 
I just tried the latest version and got an error `AttributeError: 'str' object has no attribute 'decode'`, which is caused by line 191 in `PhaseNet/phasenet//predict.py`
```python
...
fname_batch = [x.decode() for x in fname_batch]
...
```

I notice that this line was added in the latest change https://github.com/AI4EPS/PhaseNet/commit/9f551ca060749ac819a76a76e1ab0ad44f0bcf1c

Is this error due to any change in the input data format?

**Comment by tt123890** [comment]
"Did you solve it?"

**Comment by tt123890** [comment]
因为csv中的数据名称和mseed数据名称不一致

**Comment by zhong-yy** [comment]
> 因为csv中的数据名称和mseed数据名称不一致
> 
> 
> 
> 

名称是一致，我忘记当时怎么解决的了
