### ISSUE TITLE
No file matching file pattern

### ISSUE THREAD

**Issue by daihz** [AI4EPS/PhaseNet#64]
When I was using the example in Batch prediction

For sac format:
`python phasenet/predict.py --model=model/190703-214543 --data_list=test_data/sac.csv --data_dir=test_data/sac --format=sac --plot_figure`

The error report is ：

> Traceback (most recent call last):
>   File "phasenet/predict.py", line 266, in <module>
>     main(args)
>   File "phasenet/predict.py", line 249, in main
>     data_reader = DataReader_pred(
>   File "C:\Users\Desktop\PhaseNet-master\phasenet\data_reader.py", line 703, in __init__
>     self.X_shape = self.get_data_shape()
>   File "C:\Users\Desktop\PhaseNet-master\phasenet\data_reader.py", line 712, in get_data_shape
>     meta = self.read_sac(os.path.join(self.data_dir, base_name))
>   File "C:\Users\Desktop\PhaseNet-master\phasenet\data_reader.py", line 332, in read_sac
>     mseed = obspy.read(fname)
>   File "C:\Users\.conda\envs\torch1.8\lib\site-packages\decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "C:\Users\.conda\envs\torch1.8\lib\site-packages\obspy\core\util\decorator.py", line 300, in _map_example_filename
>     return func(*args, **kwargs)
>   File "C:\Users\.conda\envs\torch1.8\lib\site-packages\obspy\core\stream.py", line 212, in read
>     st = _generic_reader(pathname_or_url, _read, **kwargs)
>   File "C:\Users\.conda\envs\torch1.8\lib\site-packages\obspy\core\util\base.py", line 698, in _generic_reader
>     raise Exception("No file matching file pattern: %s" % pathname)
> 
> Exception: No file matching file pattern: test_data/sac\CI.BOM.2020-10-01T00:00.HH*

I found that in the code of data_reader, 
read_mseed( ) (from lines 295 to 328)is same as read_sac( ) (from lines 330 to 362)
I suppose that is the reason for error. Please check it. Thank you.

**Comment by zhuwq0** [comment]
Hi, I think this is because in Windows, you need to "\" instead of "/"

**Comment by daihz** [comment]
> 
Thank you.
I had solved the problem. After unziped test_data.zip ,the data names had changed. That caused the difference between data names and fnames in .csv file.

from
`CI.BOM.2020-10-01T00**:**00.HHZ.sac`    

changed  into 
`CI.BOM.2020-10-01T00**_**00.HHZ.sac` 

> Hi, I think this is because in Windows, you need to "" instead of "/"
