### ISSUE TITLE
Getting different time and probability when changing the input stream length.

### ISSUE THREAD

**Issue by saeedsltm** [AI4EPS/PhaseNet#74]
Hi,
When trying to change the input stream length (from 10 min to 1 houre), I'm getting different time and probability of P and S phases. That causes when assocciating phases, in some cases we missed events. I can't undrestand why changing the input stream length would affect picking phases?

**Comment by zhuwq0** [comment]
Hi, this is mainly because of the data normalization: https://github.com/AI4EPS/PhaseNet/blob/1d7ea66a8f1e68b1284e39e0bf8524079790f1ed/phasenet/data_reader.py#L64

**Comment by saeedsltm** [comment]
Hi @zhuwq0,
Ok, so is there any preferred time window? Should we avoid passing long streams like a day (86400s)?

**Comment by zhuwq0** [comment]
Hi, the moving window normalization should not be strongly dependent on the window size. The location of the event within the moving window will cause the difference. You can see this paper: https://pubs.geoscienceworld.org/ssa/srl/article-abstract/doi/10.1785/0220230003/620893/A-Mitigation-Strategy-for-the-Prediction

**Comment by saeedsltm** [comment]
Hi,
Thank you very much. I will go through the paper, and so I close this issue.

**Comment by ev-anderson** [comment]
Hi @zhuwq0 ,

I saw this thread and read the paper you suggested previously: https://pubs.geoscienceworld.org/ssa/srl/article-abstract/doi/10.1785/0220230003/620893/A-Mitigation-Strategy-for-the-Prediction.


I was curious how I could implement the approach suggested by Park et al. and adjust the overlap length? 

Editing "shift = window // 2" line in data_reader.py?

Thanks!

**Comment by zhuwq0** [comment]
If you are dealing with a very dense earthquake sequence, you can first try to pass a large sample rate in the prediction command, it has the effect to make the sequence sparser. 
I did not have a robust small shifted window implemented in the code.
