### ISSUE TITLE
requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by Pengling2022** [AI4EPS/PhaseNet#75]
Hello, 
I have this error when running the sample code, how should I solve it?
I used pycharm
![image](https://github.com/AI4EPS/PhaseNet/assets/96044614/a395a1c1-0a4d-4e26-b858-04135cfcf585)

**Comment by Pengling2022** [comment]
thank you!

**Comment by zhuwq0** [comment]
Hi it should be fixed now. Could you have a try?

**Comment by Pengling2022** [comment]
Ok,I will try？Is it convenient to share a h5 file of a trained model?

thank you！




| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Weiqiang ***@***.***> |
| Date | 08/11/2023 05:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [AI4EPS/PhaseNet] requests.exceptions.ConnectionError (Issue #75) |

Hi it should be fixed now. Could you have a try?

**Comment by zhuwq0** [comment]
I do not have a h5 model. The pre-trained model is here: https://github.com/AI4EPS/PhaseNet/tree/master/model/190703-214543

**Comment by Pengling2022** [comment]
Okay, thank you very much！



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Weiqiang ***@***.***> |
| Date | 08/11/2023 06:23 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [AI4EPS/PhaseNet] requests.exceptions.ConnectionError (Issue #75) |

I do not have a h5 model. The pre-trained model is here: https://github.com/AI4EPS/PhaseNet/tree/master/model/190703-214543
