### ISSUE TITLE
Example Gradio "ValueError: The current space is in the invalid state: RUNTIME_ERROR"

### ISSUE THREAD

**Issue by iqram1337** [AI4EPS/PhaseNet#83]
![Screenshot 2023-12-14 191226](https://github.com/AI4EPS/PhaseNet/assets/70354749/bfa63a37-6b53-4b0c-9aed-dae03825b7c5)
can anyone help me with this error? thank you

**Comment by zengxin1016** [comment]
are you solve this problem?could you tell me how to solve that? I also meet this question.

**Comment by zhuwq0** [comment]
Please use the FastAPI example: https://ai4eps.github.io/PhaseNet/example_fastapi/

**Comment by zengxin1016** [comment]
Thank you!I ran the code successfully.&nbsp;


曾欣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Weiqiang ***@***.***&gt;; 
发送时间: 2024年1月9日(星期二) 凌晨0:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [AI4EPS/PhaseNet] Example Gradio &quot;ValueError: The current space is in the invalid state: RUNTIME_ERROR&quot; (Issue #83)





 
Please use the FastAPI example: https://ai4eps.github.io/PhaseNet/example_fastapi/

**Comment by iqram1337** [comment]
I actually don't, byt Im using fastapi. I deployed local API via Docker and it works perfectly find.
    Pada Senin, 8 Januari 2024 pukul 21.21.26 WIB, zengxin1016 ***@***.***> menulis:  
 
 


are you solve this problem?could you tell me how to solve that? I also meet this question.

**Comment by zengxin1016** [comment]
> I actually don't, byt Im using fastapi. I deployed local API via Docker and it works perfectly find. Pada Senin, 8 Januari 2024 pukul 21.21.26 WIB, zengxin1016 ***@***.***> menulis:
Thank you for your reply！I will try it by Docker.
